



// tag::istio-installation[]

[#istioInstall]
== Installing {istio}

This section guides you through setting up and configuring the Istio Service Mesh.
Installing {istio} is a requirement for using Shared Cluster feature.

The {istio} chart can be found at https://apps.rancher.io/applications/istio.

// IMPORTANT::
// SUSE does not offer application support for {istio}.
// For support requests, contact link:https://istio.io/[Istio].

// TODO: when available, add information from SAP regarding to shared cluster.

=== Deploying the chart

// TODO: when available, double-check that link includes istio as a requirement and
//       add additional links if necessary
Before deploying {istio}, ensure that the requirements described at https://me.sap.com/notes/3247839 are met.

To deploy the chart, create the related namespace and *imagePullSecret* first.

To create the namespace, run:

[source, bash, subs="attributes"]
----
kubectl create namespace {istio_namespace}
----

[#istioIPS]
Instructions how to create the *imagePullSecret* can be found in <<imagePullSecret>>.

[#istioLIR]
Before you can install the application, you need to log in to the registry.
You can find the instructions in <<LoginApplicationCollection>>.

NOTE: The *{istio_namespace}* namespace, *imagePullSecret*, and registry login established for {istio} will be reused by:
{kiali} at <<kialiInstall>>, {prometheus} at <<prometheusInstall>>, and {grafana} at <<grafanaInstall>>.

Create a file _values.yaml_ to store some configurations for the {istio} Helm chart.
The configuration might look like the following:

[source, yaml]
----
base:
  enabled: true
cni:
  enabled: false
gateway:
  enabled: true
  # Optional: Enable support for HTTP/1.0 protocol
  env:
    ISTIO_META_HTTP10: 1
global:
  imagePullSecrets:
    - name: application-collection
istiod:
  enabled: true
  # Optional: Enable support for HTTP/1.0 protocol
  env:
    PILOT_HTTP10: 1
  # Optional: Preserve original client IP by specifying the number of trusted proxies
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
ztunnel:
  enabled: false
----

NOTE: Adjust `numTrustedProxies` based on your infrastructure.
For more details, refer to the official {istio} documentation at 
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Topology-num_trusted_proxies.

To install the application, run:
[source, bash, subs="attributes"]
----
helm install istio oci://dp.apps.rancher.io/charts/istio \
-f values.yaml \
--namespace={istio_namespace} \
--version {istio_version}
----

// end::istio-installation[]

// tag::monitoring-kiali-installation[]

[#kialiInstall]
== Installing {kiali}

The {kiali} chart can be found at https://apps.rancher.io/applications/kiali.

// IMPORTANT::
// SUSE does not offer application support for {kiali}.
// // For support requests, contact link:https://kiali.io/[Istio].

// TODO: when available, add information from SAP regarding to shared cluster.

=== Deploying the chart

// TODO: when available, double-check that link includes kiali as a requirement and
//       add additional links if necessary
Before deploying {kiali}, ensure the following prerequisites are met:

* All requirements specified in https://me.sap.com/notes/3247839 are fulfilled.
* The {istio} application is already deployed. If not, refer to <<istioInstall>> for deployment instructions.
* The {prometheus} application is already deployed. If not, refer to <<prometheusInstall>> for deployment instructions.

[#kialiIPS]
Deploy {prometheus} into the *{istio_namespace}* namespace, which should already be configured with an *imagePullSecret*,
as this is a prerequisite for {istio} at <<istioInstall>>.
For instructions on how to create the *imagePullSecret*, refer to <<imagePullSecret>>.

[#kialiLIR]
Before you can install the application, you need to log in to the registry. You can find the instructions in <<LoginApplicationCollection>>.

Create a file _values.yaml_ to store some configurations for the {kiali} Helm chart.
The configuration might look like the following:

[source, yaml]
----
external_services:
  grafana:
    auth:
      type: basic
      username: <user>
      password: <pass>
    dashboards:
      - name: Istio Performance Dashboard
    enabled: true
    external_url: http://grafana.istio-system
    internal_url: http://grafana.istio-system
  prometheus:
    custom_metrics_url: http://prometheus-server.istio-system
    url: http://prometheus-server.istio-system
global:
  imagePullSecrets:
    - application-collection
----

To install the application, run:
[source, bash, subs="attributes"]
----
helm install kiali oci://dp.apps.rancher.io/charts/kiali \
-f values.yaml \
--namespace={kiali_namespace} \
--version {kiali_version}
----

// end::monitoring-kiali-installation[]

// tag::monitoring-prometheus-installation[]

[#prometheusInstall]
== Installing {prometheus}

The {prometheus} chart can be found at https://apps.rancher.io/applications/prometheus.

// IMPORTANT::
// SUSE does not offer application support for {prometheus}.
// For support requests, contact link:https://prometheus.io/[Prometheus].

// TODO: when available, add information from SAP regarding to shared cluster.

=== Deploying the chart

// TODO: when available, double-check that link includes prometheus as a requirement and
//       add additional links if necessary
Before deploying {prometheus}, ensure that the requirements described at https://me.sap.com/notes/3247839 are met. 

[#prometheusIPS]
Deploy {prometheus} into the *{istio_namespace}* namespace, which should already be configured with an *imagePullSecret*,
as this is a prerequisite for {istio} at <<istioInstall>>.
For instructions on how to create the *imagePullSecret*, refer to <<imagePullSecret>>.

[#prometheusLIR]
Before you can install the application, you need to log in to the registry. You can find the instructions in <<LoginApplicationCollection>>.

Create a file _values.yaml_ to store some configurations for the {prometheus} Helm chart.
The configuration might look like the following:

[source, yaml]
----
alertmanager:
  persistentVolume:
    storageClassName: longhorn
global:
  imagePullSecrets:
    - application-collection
server:
  persistentVolume:
    storageClassName: longhorn
----

To install the application, run:
[source, bash, subs="attributes"]
----
helm install prometheus oci://dp.apps.rancher.io/charts/prometheus \
-f values.yaml \
--namespace={prometheus_namespace} \
--version {prometheus_version}
----

// end::monitoring-prometheus-installation[]

// tag::monitoring-grafana-installation[]

[#grafanaInstall]
== Installing {grafana}

The {grafana} chart can be found at https://apps.rancher.io/applications/grafana.

// IMPORTANT::
// SUSE does not offer application support for {grafana}.
// For support requests, contact link:https://grafana.com/[Grafana].

// TODO: when available, add information from SAP regarding to shared cluster.

=== Deploying the chart

// TODO: when available, double-check that link includes grafana as a requirement and
//       add additional links if necessary
Before deploying {grafana}, ensure that the requirements described at https://me.sap.com/notes/3247839 are met.

[#grafanaIPS]
Deploy {grafana} into the *{istio_namespace}* namespace, which should already be configured with an *imagePullSecret*,
as this is a prerequisite for {istio} at <<istioInstall>>.
For instructions on how to create the *imagePullSecret*, refer to <<imagePullSecret>>.

[#grafanaLIR]
Also, before you install the application, ensure you are logged into the registry; you will find those instructions in <<LoginApplicationCollection>>.

Create a file _values.yaml_ to store some configurations for the {grafana} Helm chart.
The configuration might look like the following:

[source, yaml]
----
adminUser: <user>
adminPassword: <pass>
global:
  imagePullSecrets:
    - application-collection
----

To install the application, run:
[source, bash, subs="attributes"]
----
helm install grafana oci://dp.apps.rancher.io/charts/grafana \
-f values.yaml \
--namespace={grafana_namespace} \
--version {grafana_version}
----

// end::monitoring-grafana-installation[]

// tag::shared-cluster-namespaces[]

== (//TODO) Adding Namespaces to Service Mesh

The following namespaces are required by {eic}. They must be created and injected to the Service Mesh:

* edgelm
* edgelm
* edge-icell
* edge-icell-secrets
* edge-icell-ela
* edge-icell-services

To establish these namespaces, create a file named _edge-namespaces.yaml_ with the definitions below:

[source, bash]
----
cat <<EOF > edge-namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: edgelm
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-icell
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-icell-services
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-icell-secrets
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-icell-ela
  labels:
    istio-injection: enabled
EOF
----

After creating the file, apply it to your cluster:
[source, bash, subs="attributes"]
----
kubectl apply -f edge-namespaces.yaml
----

// end::shared-cluster-namespaces[]

// tag::shared-cluster-permissions[]

== (//TODO) Configuring the Permissions

// TODO: to be validated with SAP scenario
// TODO: review the steps and add links

To ensure {elm} and {eic} operate properly, you need to create a dedicated user and assign it the necessary roles within your downstream Kubernetes cluster.
This user will then be used to manage and interact with the cluster resources required by {elm} and {eic}.

{rancher} simplifies access to downstream user clusters through impersonation, allowing it to act on behalf of a user.
This capability is crucial for managing permissions effectively without directly exposing sensitive credentials.
For {elm} and {eic}, you will create a new user in Rancher and grant them specific cluster roles.

_(//TODO) - steps or guide to create a New User in Rancher_

// end::shared-cluster-permissions[]

// tag::shared-cluster-kubeconfig[]

== (//TODO) Generating the Kubeconfig file for EdgeLM
// TODO: when available, explain how to generate the KUBECONFIG.

To enable {eic} and {elm} to interact with your Kubernetes cluster, you will need a kubeconfig file tailored to the specific user you configured with the necessary permissions in the previous step.
This kubeconfig file acts as a credential, allowing authenticated access to your downstream cluster.

You will download this kubeconfig directly from {rancher}, using the user account that has been granted the appropriate roles.

_(//TODO) - steps or guide to Download a Kubeconfig from Rancher_

// end::shared-cluster-kubeconfig[]

// tag::shared-cluster-registration[]
== (//TODO) Registrating the Cluster in {elm}

// // TODO: when available, link to SAP cluster registration
_(//TODO) - steps or guide to Register the Cluster in ELM_

// end::shared-cluster-registration[]
