== Do not import the whole document at once!!!

# tag::disclaimer-EIC-sizing[]
NOTE: This guide does not contain information about sizing your landscapes. Visit 
https://help.sap.com/docs/integration-suite?locale=en-US and search for the "Edge Integration Cell Sizing Guide".

# end::disclaimer-EIC-sizing[]



# tag::disclaimer-annotation[]
NOTE: In this guide, we use $ and # for shell commands, where # means that the command needs to be executed as a root user and
$ means that the command can be run by any user.

# end::disclaimer-annotation[]


# tag::disclaimer-production-versions[]
IMPORTANT: If you want to use different versions of {slem}, {rancher}, {rke} or {lh}, make sure to check the support matrix for the related solutions you want to use:
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/ +
For {redis} and {pg}, make sure to pick versions compatible to {eic}, which can be found in https://me.sap.com/notes/3247839 . +
Other versions of {metallb} or {cm} can be used but may have not been tested. 

# end::disclaimer-production-versions[]