



// tag::istio-installation[]

== Installing {istio}

// IMPORTANT::
// SUSE does not offer support for {istio}.
// For support requests, contact link:https://istio.io/[Istio community].

The {istio} chart can be found at https://apps.rancher.io/applications/istio.

NOTE: Keep in mind that the descriptions and instructions provided may differ from the 
deployment requirements for your specific infrastructure and use cases.

// TODO: when available, add information from SAP regarding to shared cluster.


=== Deploying the chart

// TODO: when available, double-check that link includes istio as a requirement and
//       add additional links if necessary
Before deploying {istio}, ensure that the requirements described at
https://me.sap.com/notes/3247839 are met.

To deploy the chart, create the related namespace and *imagePullSecret* first.
To create the namespace, run:

[source, bash, subs="attributes"]
----
kubectl create namespace {istio_namespace}
----

[#istioIPS]
Instructions how to create the *imagePullSecret* can be found in <<imagePullSecret>>.


[#istioLIR]
Before you can install the application, you need to log in to the registry. You can find the instructions in <<LoginApplicationCollection>>.

Create a file _values.yaml_ to store some configurations for the {istio} Helm chart.
The configuration might look like the following:

[source, yaml]
----
base:
  enabled: true
cni:
  enabled: false
gateway:
  enabled: true
  env:
    ISTIO_META_HTTP10: 1
global:
  imagePullSecrets:
    - name: application-collection
istiod:
  enabled: true
  env:
    PILOT_HTTP10: 1
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
ztunnel:
  enabled: false
----

NOTE: Adjust `numTrustedProxies` based on your infrastructure.
For more details, refer to the official {istio} documentation at 
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Topology-num_trusted_proxies.

To install the application, run:
[source, bash, subs="attributes"]
----
helm install istio oci://dp.apps.rancher.io/charts/istio \
-f values.yaml \
--namespace={istio_namespace} \
--version {istio_version}
----

# end::istio-installation[]

// tag::shared-cluster-permissions[]

// TODO: review this section when we decide how to generate the KUFECONFIG file for EdgeLM
== (//TODO) Cluster namespaces

The following namespaces are essential for {eic} to operate correctly.
Create a file named _edge-namespaces.yaml_ with the definitions below:

[source, bash]
----
cat <<EOF > edge-namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: edgelm
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-icell
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-icell-services
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-icell-secrets
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-icell-ela
  labels:
    istio-injection: enabled
EOF
----

After creating the file, apply it to your cluster:
[source, bash, subs="attributes"]
----
kubectl apply -f edge-namespaces.yaml
----

== Cluster permissions

To ensure {elm} and {eic} operate properly, the following Role, ClusterRole, RoleBinding and ClusterRoleBinding are needed.
// TODO: when available, apply the provided RBAC in YAML files.
(//TODO...)

== Generate the Kubeconfig file.
// TODO: when available, explain how to generate the KUBECONFIG.
(//TODO...)

// == Cluster registration in {elm}

// // TODO: when available, link to SAP cluster registration
// (//TODO...)

# end::shared-cluster-permissions[]